language: php
php:
  - 5.6
  - 7

services:
  - redis-server

env:
  global:
    - BRANCH=master
    - REPO=nc
  matrix:
    - DB=mysql

matrix:
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql BRANCH=stable10
    - php: 5.6
      env: DB=mysql BRANCH=stable11
    - php: 5.6
      env: DB=mysql BRANCH=stable12



install: ./tests/travis/install-$REPO-$BRANCH.sh

# Note the install script should make sure we are in the apps/ojsxc directory
script:
  - composer install
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=unit-coverage.xml
  - ./vendor/bin/phpunit -c phpunit.integration.xml --coverage-clover=integration-coverage.xml
  - cat ../../data/nextcloud.log
  - vendor/bin/php-cs-fixer fix --dry-run --using-cache=no
  - rm -r build/ && rm -r vendor/ && ../../occ app:check-code ojsxc

after_success:
  - bash <(curl -s https://codecov.io/bash)
