language: php
php:
  - 5.6
  - 7

services:
  - redis-server

env:
  global:
    - BRANCH=master
    - REPO=nc
  matrix:
    - DB=mysql

matrix:
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql BRANCH=stable9
    - php: 5.6
      env: DB=mysql BRANCH=stable10
    - php: 5.6
      env: DB=mysql BRANCH=stable11



install: ./tests/travis/install-$REPO-$BRANCH.sh

# Note the install script should make sure we are in the apps/ojsxc directory
script:
  - composer install
  - ./vendor/bin/phpunit -c phpunit.xml
  - ./vendor/bin/phpunit -c phpunit.integration.xml
  - cat ../../data/nextcloud.log  || cat ../../data/owncloud.log # in stable9 the log file is still called owncloud.log
